### ISSUE TITLE
Presenters have links to TasksRepository. Todo-mvp.

### ISSUE THREAD

**Issue by NikitaKozlov** [android/architecture-samples#77]
I have a small question, about relation between Presenters and TaskRepository.

Why all Presenters, but `AddEditTaskPresenter`, have link directly to `TasksRepository`, instead of `TasksDataSource`? Using interface will make code a little bit more decoupled, since interface provides all required methods.

If this behaviour is intended, then, probably, `AddEditTaskPresenter` should also have link directly to `TasksRepository`.

**Comment by tiandee** [comment]
+1

**Comment by JoseAlcerreca** [comment]
The AddEdit feature has nothing special so this should be consistent, that's a bug. We can make the `mTasksRepository` a `TasksDataSource` in every presenter, but the constructor parameter is set as a `TasksRepository` to help users choose a `TasksDataSource` when creating the presenter.

**Comment by Kaerdan** [comment]
@JoseAlcerreca But this is a design problem of the data layer, Presenter doesn't have to do anything with it. Probably modifying data layer will be a bit cleaner, then coupling to an implementation, since this is an example of the architecture.

It looks more or less ok for "todo-mvp" example, but since consistency should be kept between examples, then we should consider them as well.
For example todo-mvp-dagger: Injecting a concrete class with a dagger instead of interface doesn't look right, since your component won't provide you with anything but `TasksRepository `.
Also in todo-mvp-clean example it looks weird that all UseCases have links to `TasksRepository `, since clean architecture is all about decoupling.

One more argument: Providing is done via the `Injection` class, and this class can return only one `TasksDataSource`. UI never called `getInstance` on any DataSources directly, so the architecture itself prevents users from using wrong `TasksDataSource`.

**Comment by JoseAlcerreca** [comment]
Well, you could mistakenly inject TasksRemoteDataSource.getInstance()  into the presenter, instead of the repository. It's the same argument in clean and dagger.

We could have an `interface TasksRemoteRepository extends TasksDataSource`, but I'm ok with the concrete class. Does anyone else have strong feelings about this?

**Comment by Kaerdan** [comment]
In dagger you need to put a qualifier if you want to inject different TasksDataSources.

Probability of injecting wrong DataSource is not that big. And UI tests will fail if you will do that.

But my main point is different. I think usage both `TasksDataSource` and `TasksRepository` is confusing. It is easier to understand when only one class acts as an entry point to the Data Layer, and according to documentation this class is `TasksDataSource`. But of course, it is up to you to decide.

**Comment by Rainer-Lang** [comment]
@Kaerdan: +1

**Comment by NikitaKozlov** [comment]
So what is the decision? Just move AddEdit feature to use `TasksRepository`?

**Comment by tunjid** [comment]
Closing as obsolete.
