### ISSUE TITLE
How should we deal with the growing repository in model layer?

### ISSUE THREAD

**Issue by ryanhoo** [android/architecture-samples#89]
In the todo project we simply have one POJO(`Task`) and we already have a bloated model layer here. It's quite common to have dozens of POJOs in a **REAL** project. And it's easy to imagine how big the repository would grow. Whenever I want to add amend something, like adding a Owner(of a Task), I have to add so many lines of code in each one of the classes in the model layer. No need to mention that we have to write so many hardcoded SQL statements. 
Is there a better way to avoid these things?

**Comment by farmazon3000** [comment]
`And it's easy to imagine how big the repository would grow`
But what is the problem with big repository?

I don't know if I understand your concern but does using POJO generators like http://www.jsonschema2pojo.org/ solvers your problem ` Whenever I want to add amend something, like adding a Owner(of a Task), I have to add so many lines of code in each one of the classes in the model layer.`?

**Comment by PopTudor** [comment]
@farmazon3000 the problem with big repository is that it becomes too large and a kind of a god object that has it all.
@ryanhoo I personally make a repository for model so if I have Task model, I have a repository for Task then later if I am creating an Owner/User model, I also create a Owner/User repository. I think this gives nice structuring because is a one-to-one relationship so to me it makes sense. If the Owner repository needs some tasks, the presenter get's the tasks then passes them to Owner repository. I'm not sure if this is the right approach but untill I find another one, this will do it.

**Comment by ryanhoo** [comment]
@PopTudor Didn't help much, but at least makes sense. I just wanna keep it simple and eliminate all those boilerplate code. Thanks anyway.

**Comment by 81813780** [comment]
I face the similar issue , for example if I want to add loadMoreTasks() method  in Repository , should I add it to TasksDataSource? if so ,I have to implements it  same in TasksLocalDataSource .  that's not what I want.  @PopTudor @farmazon3000 @ryanhoo

**Comment by PopTudor** [comment]
sorry for late answer @81813780 , you could add it only in the repository if you strictly follow the MVP example given here. The Presenter at http://bit.ly/28TauM2 it uses a TasksRepository in the constructor not a TasksLocalDatasource. Since you can't substitute the repository with other implementation with TasksLocalDatasource I think it's ok to just add methods to TasksRepository.

**Comment by 81813780** [comment]
Thanks for reply @PopTudor , it's very helpful to me .

**Comment by ryanhoo** [comment]
@PopTudor @81813780 
Sorry for later answer. 😅 

**I think it's better to define the method in the Contract interface.** 

Why?

Interface is the standard the it defines protocols for implementations to follow. Also, for those who wants to communicate with this, the methods in interface are trustworthy because you know they will be implemented.

In view-presenter layer we use xxxContract.View to hold the reference instead of using xxxFragment directly.

I got the inspiration from the View-Presenter-Contract, instead of drafting a single contract for both Repository, LocalDataSource, RemoteDataSource to follow(which is a little bit annoying). Mine contract is like this:

```
interface UserContract {

   interface Local {
       Observable<User> user();

       // database only
       boolean update(User user);
       boolean delete(User user);
       ...
  }

  interface Remote {
       Observable<User> user();
  }

  Observable<User> user(boolean forceUpdate);
}
```
And then I implement `LocalUserDataSource` to handle local db operations, `RemoteUserDataSource` to handle network request. And finally our UserRepository comes:

```
class UserRepository {
   UserContract.Local mLocalDataSource;
   UserContract.Remote mRemoteDataSource;

   public static UserRepository getInstance(){
      ...
   }

   public Observable<User> user(boolean forceUpdate) {
      Observable<User> local = mLocalDataSource.user();
      Observable<User> remote = mRemoteDataSource.user()
                  .doOnNext user -> mLocalDataSource.save(user);
      if (forceUpdate)
            return remote;
      return Observable.concat(local, remote).first();
   }
}
```

If you need to expose more interfaces to presenters, just add it in Contract and then implement it.

**Comment by tunjid** [comment]
Closing as obsolete.
